# docker-compose.prod.yml

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
      secrets:
        - sentry_auth_token
      args:
        NEXT_PUBLIC_APP_ENV: "production"
        NEXT_PUBLIC_API_BASE: "https://beta.engineer42.ai"

        # --- Sentry sourcemap upload during build ---
        SENTRY_ORG: "engineer42"
        SENTRY_PROJECT: "javascript-nextjs"
        SENTRY_RELEASE: ${SENTRY_RELEASE}
    env_file:
      - ./deploy/frontend.prod.env
    environment:
      - NEXT_PUBLIC_APP_ENV=production
      - NEXT_PUBLIC_API_BASE=https://beta.engineer42.ai
      # --- Sentry tags ---
      - SENTRY_ENVIRONMENT=production
      - SENTRY_RELEASE=${SENTRY_RELEASE}
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - appnet

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.backend
    env_file:
      - ./deploy/backend.prod.env
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - appnet

  redis:
    image: redis/redis-stack:7.4.0-v3
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - appnet

networks:
  appnet:

volumes:
  redis_data:

secrets:
  sentry_auth_token:
    file: /home/ubuntu/.secrets/sentry_auth_token